version: 2.1
jobs:
  build-and-test:
    docker:
      image: circleci/node@12.16.1
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test